name: checks
on: [push]
jobs:
  run-shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install -y --no-install-recommends shellcheck
      - run: find . -name '*.sh' -print0 | xargs -0 shellcheck
  check-grammar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: pip install -r requirements.txt
      - run: find . -name '*.md' -print0 | xargs -0 proselint
